name: Semgrep Security Scan

on:
  push:
    branches: [ main, develop, "feat/**" ]
  pull_request:
    branches: [ main, develop, "feat/**" ]

jobs:
  semgrep:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep
      run: |
        semgrep --config=p/security-audit --config=p/python --config=p/bandit --sarif --output=semgrep.sarif .
      continue-on-error: true
        
    - name: Upload Semgrep results to GitHub
      if: always()
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: semgrep.sarif
      continue-on-error: true

    - name: Upload Semgrep results as artifact
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: semgrep-results
        path: semgrep.sarif